### ISSUE TITLE
Lack of compatibility with Kirby 4.1.0

### ISSUE THREAD

**Issue by gbdesign2023** [distantnative/retour-for-kirby#340]
With Kirby 4.1.0, a blank page is displayed when I click on "Redirects" in the navigation on the left.

**Comment by distantnative** [comment]
Anything in the console?

**Comment by gbdesign2023** [comment]
Only this in the DevTools Log:

```
TypeError: t is not a function
    at Array.value (index.min.js:1:345894)
    at a.paginatedItems (index.js?1705786531:74:1829)
    at t.get (vue.min.js:11:28262)
    at t.evaluate (vue.min.js:11:29258)
    at a.paginatedItems (vue.min.js:11:31451)
    at a.g (index.js?1705786531:74:3495)
    at t._render (vue.min.js:11:45862)
    at a.r (vue.min.js:11:79765)
    at t.get (vue.min.js:11:28262)
    at new t (vue.min.js:11:28175)
error @ index.min.js:1
bn @ vue.min.js:11
yn @ vue.min.js:11
t._render @ vue.min.js:11
r @ vue.min.js:11
t.get @ vue.min.js:11
t @ vue.min.js:11
(anonym) @ vue.min.js:11
Er.$mount @ vue.min.js:11
Er.$mount @ vue.min.js:11
init @ vue.min.js:11
(anonym) @ vue.min.js:11
d @ vue.min.js:11
(anonym) @ vue.min.js:11
t._update @ vue.min.js:11
r @ vue.min.js:11
t.get @ vue.min.js:11
t @ vue.min.js:11
(anonym) @ vue.min.js:11
Er.$mount @ vue.min.js:11
Er.$mount @ vue.min.js:11
init @ vue.min.js:11
(anonym) @ vue.min.js:11
d @ vue.min.js:11
(anonym) @ vue.min.js:11
t._update @ vue.min.js:11
r @ vue.min.js:11
t.get @ vue.min.js:11
t @ vue.min.js:11
(anonym) @ vue.min.js:11
Er.$mount @ vue.min.js:11
Er.$mount @ vue.min.js:11
(anonym) @ index.min.js:1
```

**Comment by distantnative** [comment]
https://github.com/distantnative/retour-for-kirby/releases/tag/5.1.0

**Comment by gbdesign2023** [comment]
@distantnative Thank you very much for your quick response. The speed at which errors are corrected is amazing. In the new version, my links are no longer displayed as UUIDs. This was still the case in v5.0.

**Comment by distantnative** [comment]
@gbdesign2023 should be displayed as proper page previews, right? profiting from the link field previews from 4.1

**Comment by gbdesign2023** [comment]
@distantnative Yes, everything is displayed as expected. Many thanks for the fix 🤙
